### ISSUE TITLE
IE 11 Fails To Load Applications

### ISSUE THREAD

**Issue by geoff5802** [BigRoomStudios/strangeluv#30]
A issue inherited from "React-redux-starter-kit", details can be seen here: https://github.com/davezuko/react-redux-starter-kit/issues/785

The PR for that issue can be seen here - https://github.com/creatorkuang/react-redux-starter-kit/commit/dcb1c88c03d65b79c8ec70d63d2ef3e2236ffa84

We just need to update config/main.js to reflect their changes and it seems to solve the issue at hand. # @

**Comment by devinivy** [comment]
Resolved in #31
